version: "3.3"
services:
  ubuntu-bionic:
    build:
      context: ./
      dockerfile: ./ubuntu-bionic/Dockerfile
    image: every-distro:ubuntu-bionic
  arch:
    build:
      context: ./
      dockerfile: ./arch/Dockerfile
    image: every-distro:arch