version: "3.3"
services:
  ubuntu-bionic:
    build:
      context: ./
      dockerfile: ./ubuntu-bionic/Dockerfile
    image: every-distro:ubuntu-bionic
  arch:
    build:
      context: ./
      dockerfile: ./arch/Dockerfile
    image: every-distro:arch
  ubuntu-disco:
    build:
      context: ./
      dockerfile: ./ubuntu-disco/Dockerfile
    image: every-distro:ubuntu-disco
  alpine:
    build:
      context: ./
      dockerfile: ./alpine/Dockerfile
    image: every-distro:alpine
  nginx:
    build: ./nginx
    image: every-distro:nginx
    ports:
      - "6900:80"
    links:
      - ubuntu-bionic
      - arch
      - ubuntu-disco
      - alpine
      - centos7
      - centos6
  centos7:
    build:
      context: ./
      dockerfile: ./centos7/Dockerfile
    image: every-distro:centos7
  centos6:
    build:
      context: ./
      dockerfile: ./centos6/Dockerfile
    image: every-distro:centos6
  amazonlinux:
    build:
      context: ./
      dockerfile: ./amazonlinux/Dockerfile
    image: every-distro:amazonl